#applicable types - "MySQL", "MariaDB" & "MongoDB"
storage-method: "MySQL"
database:
  mysql:
    host: "localhost"
    port: 3306
    database: "practice"
    username: "practice"
    password: "s0DlbR2zitaphuneB8sp"
  mongodb:
    connection-string: ""

gang:
  #how often should gang data be backed up?
  save-interval: 10 #time in minutes
  leaderboard-interval: 15 #time in minutes
  leaderboard-data-pull-amount: 15 #for gang top, how many of the top gangs data should be loaded?
  name_regex: '^[a-zA-Z0-9]+$' #so gang names can only be numbers and letters, change this at ur own risk
  command:
    enable_invsee: true #Enable the /gang invsee command?
  blacklisted_names: #applies to gang name
    - nigger
    - fuck
    - shit
    - cunt
    - dickhead
  blacklisted_words: #applies to gang description
    - nigger
    - fuck
    - shit
    - cunt
    - n11ga
  player_actions: #should GangsX globally broadcast these actions?
    join_gang: true
    leave_gang: true
    kicked_from_gang: true
    leader_changed: true
    disband_gang: true
    rename_gang: true
  command_cooldowns: #time in seconds
    alert: 15
    rename: 300
  roles:
    prefixes:
      leader: '&8[&4Leader&8]'
      co-leader: '&8[&dCo-Leader&8]'
      mod: '&8[&cMod&8]'
      member: '&8[&aMember&8]'
      recruit: '&8[&7Recruit&8]'
    icons: #displayed in gang info
      leader: '***'
      co-leader: '**'
      mod: '*'
      member: '+'
      recruit: '-'
  name_min_length: 3
  name_max_length: 16
  bank:
    #Should we limit the amount that gangs can store inside the gang bank?
    #NOTE: this value shouldn't be below the maximum upgrade value
    limit_enabled: false
    limit: 1000000000000
  maximum_level: 10
  default_description: 'No description set :('
  ally_chat_format: "&f[&dAlly-Chat&f] &7(%gang%) &7%player%: &d%message%"
  chat_format: "&f[&bGang-Chat&f] &7%role% &7%player%: &b%message%"
  social_spy_format: "&f[&bGang-Spy&f] &7(%gang%) %role% &7%player%&7: &b%message%"
  default_permissions:
    BANK_DEPOSIT: 'MOD'
    BANK_WITHDRAW: 'MOD'
    CHANGE_DESCRIPTION: 'MOD'
    MANAGE_RELATIONS: 'CO_LEADER'
    PURCHASE_VALUE: 'MOD'
    PURCHASE_UPGRADES: 'CO_LEADER'
    PROMOTE: 'CO_LEADER'
    DEMOTE: 'CO_LEADER'
    MANAGE_FRIENDLY_FIRE: 'LEADER'
    KICK: 'CO_LEADER'
    RENAME_GANG: 'LEADER'
    SHOP: 'MOD'
    INVSEE: 'MEMBER'
    INVITE: 'CO_LEADER'

upgrades:
  home_limit:
    maximum_level: 2
    stages:
      1:
        value: 3
        cost: 100000
      2:
        value: 5
        cost: 250000
levels:
  2:
    requirements:
      blocksmined: 1000
      playerkills: 5
      bankbalance: 1000000
      kothwins: 0
    requirements_message:
      - ''
      - '&c&lGang Levelup Failure'
      - '&fYou need the following for this level:'
      - ''
      - '&c&l | &fBank Balance: &c$1M'
      - '&c&l | &fBlocks Mined: &c1k'
      - '&c&l | &fPlayer Kills: &c5'
      - ''
    levelup_commands:
      - 'gadmin setmaxmembers %gang% 6'
      - 'gadmin addcoins %gang% 5'
    levelup_message:
      - ''
      - '&a&lGang Levelup &8- &5&lLevel 2'
      - '&fCongrats on leveling up, you have unlocked:'
      - ''
      - '&d&l | &f6 Gang Member Limit'
      - '&d&l | &f10x Gang Coins'
      - ''
  3:
    requirements:
      blocksmined: 10000
      playerkills: 25
      bankbalance: 5000000
      kothwins: 0
    requirements_message:
      - ''
      - '&c&lGang Levelup Failure'
      - '&fYou need the following for this level:'
      - ''
      - '&c&l | &fBank Balance: &c$5M'
      - '&c&l | &fBlocks Mined: &c10k'
      - '&c&l | &fPlayer Kills: &c25'
      - ''
    levelup_commands:
      - 'gadmin setmaxhomes %gang% 2'
      - 'gadmin addcoins %gang% 15'
    levelup_message:
      - ''
      - '&a&lGang Levelup &8- &3&lLevel 3'
      - '&fCongrats on leveling up, you have unlocked:'
      - ''
      - '&b&l | &f2 Gang Homes'
      - '&b&l | &f15x Gang Coins'
      - ''
  4:
    requirements:
      blocksmined: 50000
      playerkills: 50
      bankbalance: 25000000
      kothwins: 0
    requirements_message:
      - ''
      - '&c&lGang Levelup Failure'
      - '&fYou need the following for this level:'
      - ''
      - '&c&l | &fBank Balance: &c$25M'
      - '&c&l | &fBlocks Mined: &c50k'
      - '&c&l | &fPlayer Kills: &c50'
      - ''
    levelup_commands:
      - 'gadmin giveupgrade colourdescription'
      - 'gadmin addcoins %gang% 15'
    levelup_message:
      - ''
      - '&a&lGang Levelup &8- &6&lLevel 4'
      - '&fCongrats on leveling up, you have unlocked:'
      - ''
      - '&e&l | &cC&6o&el&ao&3u&9r&5e&cd &fGang Description'
      - '&e&l | &f15x Gang Coins'
      - ''