#applicable types - "MySQL", "MariaDB" & "MongoDB"
storage-method: "MariaDB"
database:
  mysql:
    host: "host"
    port: 3306
    database: "database"
    username: "username"
    password: "password"
  mongodb:
    connection-string: ""

gang:
  blacklisted_names:
    - nigger
    - fuck
    - shit
    - cunt

shop:
  #what should the currency for the shop be? (coins or bankBalance)
  currency: "coins"