#applicable types - "MySQL", "MariaDB" & "MongoDB"
storage-method: "MySQL"
database:
  mysql:
    host: "host"
    port: 3306
    database: "database"
    username: "username"
    password: "password"
  mongodb:
    connection-string: ""

gang:
  #how often should gang data be backed up?
  save-interval: 10 #time in minutes
  leaderboard-interval: 15 #time in minutes
  leaderboard-data-pull-amount: 15 #for gang top, how many of the top gangs data should be loaded?
  blacklisted_names: #applies to gang name
    - nigger
    - fuck
    - shit
    - cunt
  blacklisted_words: #applies to gang description
    - nigger
    - fuck
    - shit
    - cunt
  player_actions: #should GangsX globally broadcast these actions?
    join_gang: true
    leave_gang: true
    kicked_from_gang: true
    leader_changed: true
  command_cooldowns: #time in seconds
    alert: 15
  roles:
    prefixes:
      leader: '&8[&aLeader&8]'
  name_min_length: 3
  name_max_length: 16
  bank:
    limit_enabled: false #should we limit the amount that gangs can store inside the gang bank?
    limit: 1000000000000
  maximum_level: 5
  default_description: 'No description set :('
  chat_format: "&f[&bGang-Chat&f] &7%role% &7%player%: &b%message%"
  social_spy_format: "&f[&bGang-Spy&f] &7(%gang%) %role% &7%player%&7: &b%message%"

shop:
  #what should the currency for the shop be? (coins or bankBalance)
  currency: "coins"

upgrades:
  home_limit:
    maximum_level: 2
    stages:
      1:
        value: 3
        cost: 100000
      2:
        value: 5
        cost: 250000