name: ${project.name}
description: ${project.description}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
api-version: 1.18
depend:
  - Vault
softdepend:
  - PlaceholderAPI
authors:
  - Frxq15
  - WitheredToast

commands:
  gang:
    usage: /<command>
    description: Gang Command
    aliases: [gangs, g]
  gangchat:
    usage: /<command>
    description: Gang chat command
    aliases: [gc]
  allychat:
    usage: /<command>
    description: Ally chat command
    aliases: [ac]
